# Generated by Django 3.2.9 on 2021-12-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apicar.car')),
            ],
        ),
    ]
