# Generated by Django 3.2.9 on 2021-12-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='car_id',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='apicar.Car'),
        ),
    ]
