# Generated by Django 3.2.9 on 2021-12-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0005_alter_rating_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='carid',
            field=models.ManyToManyField(null=True, related_name='ratings', to='apicar.Car'),
        ),
    ]
