# Generated by Django 3.2.9 on 2021-12-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0006_auto_20211218_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='carid',
            field=models.ManyToManyField(related_name='ratings', to='apicar.Car'),
        ),
    ]
