# Generated by Django 3.2.9 on 2021-12-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0007_alter_rating_carid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='carid',
            new_name='car_id',
        ),
    ]
