# Generated by Django 3.2.9 on 2021-12-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0009_alter_rating_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
    ]
