# Generated by Django 3.2.9 on 2021-12-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0010_rename_rating_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='car_id',
            new_name='car',
        ),
    ]
