# Generated by Django 3.2.9 on 2021-12-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0011_rename_car_id_rating_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='car',
            new_name='car_id',
        ),
    ]
