# Generated by Django 3.2.9 on 2021-12-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0012_rename_car_rating_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car_id',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='apicar.Car'),
        ),
    ]
