# Generated by Django 3.2.9 on 2021-12-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0013_alter_rating_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apicar.car'),
            preserve_default=False,
        ),
    ]
