# Generated by Django 3.2.9 on 2021-12-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0014_auto_20211218_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apicar.car'),
        ),
    ]
