# Generated by Django 3.2.9 on 2021-12-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0015_alter_rating_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apicar.car'),
        ),
    ]
