# Generated by Django 3.2.9 on 2021-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicar', '0017_alter_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
